[package]
name = "hdm-api"
description = "Local REST + WebSocket API server for Hydra Download Manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
hdm-json = { path = "../hdm-json" }
hdm-crypto = { path = "../hdm-crypto" }
hdm-core = { path = "../hdm-core" }
hdm-net = { path = "../hdm-net" }

[dev-dependencies]
hdm-testserver = { path = "../hdm-testserver" }
